import { CommonModule } from '@angular/common';
import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ReviewsService } from '../../core/services/reviews.service';
import { EmptyStateComponent } from '../../shared/components/empty-state/empty-state.component';
import { ErrorMessageComponent } from '../../shared/components/error-message/error-message.component';
import { LoadingComponent } from '../../shared/components/loading/loading.component';
import { PageHeaderComponent } from '../../shared/components/page-header/page-header.component';
import { firstArray, formatDate, pickString } from '../../shared/utils/view.utils';
@Component({selector:'app-reviews-page',standalone:true,imports:[CommonModule,FormsModule,PageHeaderComponent,LoadingComponent,ErrorMessageComponent,EmptyStateComponent],template:`
<section class="page-shell"><app-page-header title="Resenhas" subtitle="Feed de resenhas, comentários, reações e filtros por material ou trilha."></app-page-header>
<div class="grid grid-cols-1 xl:grid-cols-[1fr_360px] gap-lg"><section><div class="settings-card mb-lg"><div class="grid grid-cols-1 md:grid-cols-3 gap-md"><input class="form-control md:col-span-2" [(ngModel)]="search" placeholder="Buscar resenhas..." (keyup.enter)="load()"><button class="btn-primary justify-center" (click)="load()">Buscar</button></div></div><app-loading *ngIf="loading()"></app-loading><app-error-message *ngIf="error()" [message]="error()!"></app-error-message><app-empty-state *ngIf="!loading()&&!error()&&!reviews().length" icon="reviews" title="Nenhuma resenha encontrada" description="Crie a primeira resenha para um material."></app-empty-state><article *ngFor="let r of reviews()" class="settings-card mb-md"><div class="flex justify-between gap-3"><span class="badge badge-secondary">{{ pick(r,['type'],'resenha') }}</span><span class="text-label-sm text-on-surface-variant">{{ date(r) }}</span></div><h3 class="text-headline-sm mt-md">{{ pick(r,['title','material_title'],'Resenha sem título') }}</h3><p class="text-body-md text-on-surface-variant whitespace-pre-line">{{ pick(r,['content','text','body'],'Sem conteúdo.') }}</p><div class="flex gap-2 mt-md"><button class="btn-secondary"><span class="material-symbols-outlined text-[18px]">thumb_up</span>Útil</button><button class="btn-secondary"><span class="material-symbols-outlined text-[18px]">comment</span>Comentar</button></div></article></section><aside class="settings-card h-fit space-y-md"><h3 class="section-title">Nova resenha</h3><input class="form-control" [(ngModel)]="title" placeholder="Título"><textarea class="form-control min-h-[140px]" [(ngModel)]="content" placeholder="Escreva sua resenha..."></textarea><button class="btn-primary w-full justify-center" (click)="create()" [disabled]="saving()">{{ saving()?'Salvando...':'Publicar resenha' }}</button></aside></div></section>`})
export class ReviewsPageComponent implements OnInit{loading=signal(true);saving=signal(false);error=signal<string|null>(null);reviews=signal<Record<string,unknown>[]>([]);search='';title='';content='';constructor(private service:ReviewsService){}ngOnInit():void{this.load()}load():void{this.loading.set(true);this.service.list({q:this.search}).subscribe({next:(res)=>{this.reviews.set(firstArray<Record<string,unknown>>(res,['reviews','items','rows']));this.loading.set(false)},error:(err:Error)=>{this.error.set(err.message);this.loading.set(false)}})}create():void{this.saving.set(true);this.service.create({title:this.title,content:this.content}).subscribe({next:()=>{this.saving.set(false);this.title='';this.content='';this.load()},error:(err:Error)=>{this.error.set(err.message);this.saving.set(false)}})}pick(i:unknown,k:string[],f=''):string{return pickString(i,k,f)}date(i:unknown):string{return formatDate(pickString(i,['created_at','createdAt','date'],''))}}
