/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#d3e4fe",
        outline: "#737686",
        "primary-fixed": "#dbe1ff",
        "surface-container": "#eceef0",
        "on-tertiary-fixed": "#360f00",
        "secondary-fixed-dim": "#b7c8e1",
        "primary-container": "#2563eb",
        "on-surface-variant": "#434655",
        "surface-container-highest": "#e0e3e5",
        "on-error-container": "#93000a",
        "inverse-primary": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "on-background": "#191c1e",
        "on-secondary-fixed-variant": "#38485d",
        "on-secondary": "#ffffff",
        "outline-variant": "#c3c6d7",
        "tertiary-container": "#bc4800",
        "on-error": "#ffffff",
        "surface-dim": "#d8dadc",
        background: "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "on-secondary-fixed": "#0b1c30",
        "on-tertiary-container": "#ffede6",
        "on-primary-container": "#eeefff",
        "on-primary-fixed-variant": "#003ea8",
        tertiary: "#943700",
        "tertiary-fixed-dim": "#ffb596",
        "inverse-on-surface": "#eff1f3",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-container": "#54647a",
        "surface-container-high": "#e6e8ea",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdbcd",
        "secondary-container": "#d0e1fb",
        "surface-variant": "#e0e3e5",
        "on-surface": "#191c1e",
        surface: "#f7f9fb",
        primary: "#004ac6",
        "inverse-surface": "#2d3133",
        "primary-fixed-dim": "#b4c5ff",
        secondary: "#505f76",
        "surface-tint": "#0053db",
        "on-tertiary-fixed-variant": "#7d2d00"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "2xl": "48px",
        sm: "8px",
        md: "16px",
        xl: "32px",
        "3xl": "64px",
        lg: "24px",
        gutter: "24px",
        "container-max": "1280px",
        "sidebar-width": "260px",
        base: "4px",
        xs: "4px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    }
  },
  plugins: []
};
